### ISSUE TITLE
Feature: User can view the  library 

### ISSUE THREAD

**Issue by brandon-au** [brandon-au/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Add nav bar with links to other pages
- [ ] Add a div container: [library] to the HTML.
- [ ] Add a <UL> to the HTML
- [ ] Create dummy villager entry
![image](https://user-images.githubusercontent.com/109652009/192842147-c4ecfd6c-d597-40f8-8e30-a7785101ce19.png)

- [ ] Ensure entry looks nice on mobile and desktop
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
